openapi: 3.0.0
info:
  title: Group Management API
  version: 1.0.0
servers:
  - url: https://api2.requestly.io/v1

security:
  - ApiKeyAuth: []

paths:
  /groups:
    get:
      summary: Retrieve a list of all groups
      description: Fetches details of all the groups available in the system. Supports pagination.
      parameters:
        - in: query
          name: offset
          schema:
            type: integer
            minimum: 0
          required: false
          description: The index from where the results should start. Usually set to the value received in `nextOffset` from the previous response.
        - in: query
          name: pageSize
          schema:
            type: integer
            minimum: 1
            maximum: 75
            default: 30
          required: false
          description: Number of results to return. Maximum value is 75.
      responses:
        '200':
          description: List of groups retrieved successfully
          content:
            application/json:
              example:
                success: true
                data: 
                  - id: "Group_1a2b3c"
                    name: "Sample Group A"
                    status: "Active"
                    isFavourite: false
                  - id: "Group_4d5e6f"
                    name: "Sample Group B"
                    status: "Inactive"
                    isFavourite: true
                nextOffset: 2
                total: 10
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    description: Indicates if the fetch was successful
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Group'
                  nextOffset:
                    type: integer
                    nullable: true
                    description: The offset for the next page of results. Null if there are no more records.
                  total:
                    type: integer
                    description: Total number of records available
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadPageFilters'
        '401':
          $ref: '#/components/responses/UnauthorizedResponse'
        '500':
          $ref: '#/components/responses/InternalServerError'

components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: x-api-key

  responses:
    UnauthorizedResponse:
      description: Unauthorized action
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/CommonResponse'
    InternalServerError:
      description: An error occurred on the server
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/CommonResponse'

  schemas:
    CommonResponse:
      type: object
      properties:
        success:
          type: boolean
          description: Indicates if the operation was successful
        message:
          type: string
          description: Descriptive message about the operation result

    BadPageFilters:
      type: object
      properties:
        success:
          type: boolean
          description: Indicates if the operation was successful (false for 400 errors)
        message:
          type: string
          description: Error message describing the reason for the bad request
          enum:
            - "Offset should be a number"
            - "Offset cannot be negative"
            - "Page size should be a number"
            - "Page size cannot be negative"
    Group:
      type: object
      properties:
        id:
          type: string
          description: Unique identifier for the group
        name:
          type: string
          description: Name of the group
        status:
          type: string
          enum: [Active, Inactive]
          description: Status of the group
        isFavourite:
          type: boolean
          description: Indicates whether the group is marked as a favourite
